use std::path::PathBuf;
use serde::{Deserialize, Serialize};

/// Represents the file system artifacts generated by the MOFid decomposition process.
/// The Surface Generator uses these paths to load semantic geometry (Nodes/Linkers).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MofArtifacts {
    /// The unique name/ID of the MOF processed.
    pub name: String,
    
    /// The root directory containing all generated files for this specific MOF.
    pub output_root: PathBuf,
    
    /// Path to the directory containing .xyz/.mol files for Metal Nodes (SBUs).
    pub nodes_dir: PathBuf,
    
    /// Path to the directory containing .xyz/.mol files for Organic Linkers.
    pub linkers_dir: PathBuf,
    
    /// Path to the simplified 'underlying net' CIF (topology abstraction), if generated.
    pub underlying_net_cif: Option<PathBuf>,
    
    /// The calculated MOFid string (semantic identifier).
    pub mofid: String,
    
    /// The topology code (e.g., "pcu", "fcu"), if identified.
    pub topology: Option<String>,
}

/// Helper struct for parsing MOFid string data (internal use or metadata).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MofIdData {
    pub name: String,
    pub smiles: String,
    pub topology: String,
    pub catenation: Option<String>,
}