use crate::core::structure::{CifRepresentable, Lattice};
use anyhow::{Context, Result};
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;
use nalgebra::Vector3;

/// Writes a structure (Crystal or Slab) to a CIF file.
///
/// # Arguments
/// * `structure` - Anything that implements `CifRepresentable` (has atoms and a lattice).
/// * `path` - The output file path.
pub fn to_cif<T: CifRepresentable>(structure: &T, path: &Path) -> Result<()> {
    let file = File::create(path).with_context(|| format!("Failed to create output file: {:?}", path))?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "data_generated")?;
    
    let (a, b, c, alpha, beta, gamma) = structure.lattice().to_parameters();
    
    writeln!(writer, "_cell_length_a               {:.5}", a)?;
    writeln!(writer, "_cell_length_b               {:.5}", b)?;
    writeln!(writer, "_cell_length_c               {:.5}", c)?;
    writeln!(writer, "_cell_angle_alpha            {:.5}", alpha)?;
    writeln!(writer, "_cell_angle_beta             {:.5}", beta)?;
    writeln!(writer, "_cell_angle_gamma            {:.5}", gamma)?;
    writeln!(writer, "_space_group_name_H-M_alt    'P 1'")?;
    writeln!(writer, "loop_")?;
    writeln!(writer, " _atom_site_label")?;
    writeln!(writer, " _atom_site_type_symbol")?;
    writeln!(writer, " _atom_site_fract_x")?;
    writeln!(writer, " _atom_site_fract_y")?;
    writeln!(writer, " _atom_site_fract_z")?;

    for (i, atom) in structure.atoms().iter().enumerate() {
        // Create unique label: "C1", "H2", etc.
        let label = format!("{}{}", atom.element, i + 1);
        writeln!(
            writer, 
            " {:<8} {:<4} {:<10.5} {:<10.5} {:<10.5}", 
            label, 
            atom.element, 
            atom.fractional_coords.x, 
            atom.fractional_coords.y, 
            atom.fractional_coords.z
        )?;
    }

    writer.flush().context("Failed to flush buffer to file")?;
    Ok(())
}

/// Writes a list of Cartesian coordinates to an XYZ file (for molecular debugging).
pub fn to_xyz(atoms: &[(String, Vector3<f64>)], path: &Path) -> Result<()> {
    let file = File::create(path).with_context(|| format!("Failed to create XYZ file: {:?}", path))?;
    let mut writer = BufWriter::new(file);

    // XYZ Format:
    // Line 1: Number of atoms
    // Line 2: Comment
    // Line 3+: Element X Y Z
    
    writeln!(writer, "{}", atoms.len())?;
    writeln!(writer, "Generated by Crystal Surface Generator")?;

    for (element, pos) in atoms {
        writeln!(writer, "{:<4} {:<12.6} {:<12.6} {:<12.6}", element, pos.x, pos.y, pos.z)?;
    }

    writer.flush()?;
    Ok(())
}